unstable_features = true

array_width                         = 60
attr_fn_like_width                  = 70
binop_separator                     = "Front"
blank_lines_lower_bound             = 0
blank_lines_upper_bound             = 1
brace_style                         = "SameLineWhere"
chain_width                         = 35
color                               = "Always"
combine_control_expr                = false
comment_width                       = 80
condense_wildcard_suffixes          = true
control_brace_style                 = "ClosingNextLine"
empty_item_single_line              = true
enum_discrim_align_threshold        = 30
error_on_line_overflow              = false
error_on_unformatted                = false
fn_params_layout                    = "Tall"
fn_call_width                       = 60
fn_single_line                      = false
force_explicit_abi                  = true
force_multiline_blocks              = false
format_code_in_doc_comments         = true
doc_comment_code_block_width        = 100
format_generated_files              = true
format_macro_matchers               = true
format_macro_bodies                 = true
skip_macro_invocations              = []
format_strings                      = true
hard_tabs                           = false
hex_literal_case                    = "Upper"
ignore                              = []
imports_indent                      = "Block"
imports_layout                      = "Mixed"
indent_style                        = "Block"
inline_attribute_width              = 0
match_arm_blocks                    = true
match_arm_leading_pipes             = "Never"
match_block_trailing_comma          = true
max_width                           = 100
merge_derives                       = true
imports_granularity                 = "Crate"
newline_style                       = "Auto"
normalize_comments                  = false
normalize_doc_attributes            = false
overflow_delimited_expr             = false
remove_nested_parens                = true
reorder_impl_items                  = false
reorder_imports                     = true
group_imports                       = "StdExternalCrate"
reorder_modules                     = true
trailing_comma                      = "Vertical"         #"Never"
short_array_element_width_threshold = 10
skip_children                       = false
single_line_if_else_max_width       = 50
single_line_let_else_max_width      = 50
space_after_colon                   = true
space_before_colon                  = false
spaces_around_ranges                = false
struct_field_align_threshold        = 30
struct_lit_single_line              = true # param struct in single line
struct_lit_width                    = 35
struct_variant_width                = 18
tab_spaces                          = 4
trailing_semicolon                  = true
type_punctuation_density            = "Wide"
use_field_init_shorthand            = true
use_small_heuristics                = "Default"
use_try_shorthand                   = false
where_single_line                   = false
# warp_comments = true
# required_version = "1.4.38"
# show_parse_errors = true
