unstable_features = true

array_width = 60
attr_fn_like_width = 70
chain_width = 35
color = "Always"
condense_wildcard_suffixes = true
# control_brace_style = "ClosingNextLine"
empty_item_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
skip_macro_invocations = []
format_strings = true
hex_literal_case = "Upper"
ignore = []
match_arm_blocks = true
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = false
remove_nested_parens = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
struct_lit_width = 35
struct_variant_width = 18
use_field_init_shorthand = true
use_try_shorthand = true
